[window]
dimensions={columns=125, lines=40}

[scrolling]
history=2000

[font]
size=11.0

[font.normal]
family="Liberation Mono Nerd"

[cursor]
style={shape="Beam", blinking="Always"}

[keyboard]
bindings = [{key="T", mods="Control|Shift", action = "CreateNewWindow"}]
